#!/bin/sh
APPDIR=`dirname $0`;
java -Xmx1024m -cp "$APPDIR/src:$APPDIR/demo:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.allen_sauer.gwt.dnd.demo.DragDropDemo -style PRETTY
