#!/bin/sh
APPDIR=`dirname $0`;
$JAVA_HOME_32BIT/bin/java -Xmx1024m -cp "$APPDIR/src:$APPDIR/demo:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.allen_sauer.gwt.dnd.demo.DragDropDemo -style PRETTY -whitelist "^http[:][/][/]google[.]com/*"
